apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
stringData:
  host: amqp://user:password@rabbitmq.default.svc.cluster.local:5672 # amqp 地址
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
spec:
  secretTargetRef:
  - parameter: host
    name: keda-rabbitmq-secret
    key: host
