apiVersion: v1
kind: Pod
metadata:
  labels:
    run: etcd-grpc
  name: etcd-grpc
spec:
  containers:
  - image: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.1-0
    name: etcd-grpc
    command: [ "/usr/local/bin/etcd", "--data-dir", "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://127.0.0.1:2379", "--log-level", "debug" ]
    ports:
    - containerPort: 2379
      name: etcd-2379
    livenessProbe:
      grpc:
        port: 2379
      initialDelaySeconds: 10
      timeoutSeconds: 2
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
