apiVersion: v1
kind: Pod
metadata:
  labels:
    run: slow
  name: slow
spec:
  containers:
  - image: registry.cn-beijing.aliyuncs.com/dotbalo/slow:latest
    name: slow
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /ping
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      timeoutSeconds: 2
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 2
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 1
      timeoutSeconds: 2
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 2
    startupProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 2
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 30
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
