apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preferred-compute
  name: preferred-compute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: preferred-compute
  strategy: {}
  template:
    metadata:
      labels:
        app: preferred-compute
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - nvme
          - weight: 50
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd

      containers:
      - image: registry.cn-beijing.aliyuncs.com/dotbalo/nginx:1.15.12
        name: nginx
        resources: {}
status: {}
