apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-eureka
  name: demo-eureka
spec:
  clusterIP: None
  ports:
  - name: http-web
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: demo-eureka
  type: ClusterIP
status:
  loadBalancer: {}
