apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: demo-eureka
  name: demo-eureka
  namespace: demo
spec:
  serviceName: "demo-eureka"
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: demo-eureka
  template:
    metadata:
      labels:
        app: demo-eureka
    spec:
      containers:
      - image: crpi-fr9j2ao0rwew6bnj.cn-shanghai.personal.cr.aliyuncs.com/yurenovo/demo-eureka:v0.0.2
        imagePullPolicy: IfNotPresent
        name: demo-eureka
        ports:
        - name: http-web
          containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: SERVER_PORT
          value: '8761'
        - name: EUREKA_SERVER_ADDRESS
          value: http://demo-eureka-0.demo-eureka:8761/eureka/,http://demo-eureka-1.demo-eureka:8761/eureka/,http://demo-eureka-2.demo-eureka:8761/eureka/
        livenessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2

