apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: basic
  namespace: monitoring
spec:
  groups:
  - name: mysql
    rules:
    - alert: MySQLStatus
      annotations:
        description: "实例：{{ $labels.instance }} 故障"
        summary: "MySQL 服务宕机"
      expr: mysql_up == 0
      for: 1m
      labels:
        severity: critical
        type: basic
        component: mysql
  - name: redis
    riles:
    - alert: RedisStatus
      annotations:
        description: "实例：{{ $labels.instance }} 故障"
        summary: "Redis 服务宕机"
      expr: redis_up == 0
      for: 1m
      labels:
        severity: critical
        type: basic
        component: redis
