apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    tier: backend
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: registry.cn-beijing.aliyuncs.com/dotbalo/redis:7.2.5
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - name: tcp-6379
          containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: tcp-6379
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          tcpSocket:
            port: tcp-6379
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

