apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: 192.168.119.155/library/alpine:3.23
        command: ["/bin/sh", "-c", "sleep infinity"]
      imagePullSecrets:
      - name: harbor-key
