apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-handler
  name: demo-handler
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-handler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: demo-handler
    spec:
      containers:
        - name: demo-handler
          image: crpi-fr9j2ao0rwew6bnj.cn-shanghai.personal.cr.aliyuncs.com/yurenovo/demo-handler:v0.0.2-upgrade
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8supgrade
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          resources: {}
